# Generated by Django 5.1.1 on 2024-10-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=42)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('UN', 'Un.'), ('L', 'L'), ('KG', 'Kg')], max_length=3)),
                ('categoria', models.CharField(choices=[('PAD', 'Padaria'), ('LEG', 'Legume'), ('CAR', 'Carne'), ('FRU', 'Fruta'), ('BEB', 'Bebida')], max_length=3)),
            ],
        ),
    ]
