# Generated by Django 5.1.1 on 2024-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
